//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class feedback
    {

        public int id { get; set; }

        [Required]
        public int user_id { get; set; }


        [Required(ErrorMessage = "You have to enter a feedback .")]
        public string message { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
