//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_banking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_BankingEntities : DbContext
    {
        public E_BankingEntities()
            : base("name=E_BankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<Bill_Type> Bill_Type { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<Transcation> Transcations { get; set; }
    }
}
